const mongoose = require('mongoose');
require('dotenv').config(); //like loading varaibles from .env
const Course = require('./models/Course'); //adjust if your path is different

const courses = [
  { code: 'CSE1000', title: 'Freshman Udergraduate Research' },
  { code: 'CSE1105', title: 'Intro to Computer Science and Engineering' },  
  { code: 'CSE1106', title: 'Introduction to Computer Science and Engineering' },
  { code: 'CSE1205', title: 'Introduction to Computer Science and Engineering' },
  { code: 'CSE1301', title: 'Computer Literacy' },
  { code: 'CSE1310', title: 'Intro to Computers and Programming' },
  { code: 'CSE1311', title: 'Introduction to Programming for Engineers' },
  { code: 'CSE1320', title: 'Intermediate Programming' },
  { code: 'CSE1325', title: 'Object-Oriented Programming' },
  { code: 'CSE1392', title: 'Special Topics' },
  { code: 'CSE2000', title: 'Sophmore Undergraduate Research' },
  { code: 'CSE2100', title: 'Practical Computer Hardware/Software Systems' },
  { code: 'CSE2312', title: 'Computer Organization and Assembly' },
  { code: 'CSE2315', title: 'Discrete Structures' },
  { code: 'CSE2392', title: 'Special Topics' },
  { code: 'CSE2440', title: 'Circuit Analysis' },
  { code: 'CSE2441', title: 'Digital Logic Desgin' },
  { code: 'CSE3000', title: 'Junior Undergraduate Research' },
  { code: 'CSE3302', title: 'Programming Languages' },
  { code: 'CSE3310', title: 'Fundamentals of Software Engineering' },
  { code: 'CSE3311', title: 'Object-Oriented Software Engineering' },
  { code: 'CSE3313', title: 'Introduction to Signal Processing' },
  { code: 'CSE3314', title: 'Professional Practices' },
  { code: 'CSE3315', title: 'Theoretical Concepts in Computer Science and Engineering' },
  { code: 'CSE3318', title: 'Algorithms and Data Structures' },
  { code: 'CSE3320', title: 'Operating Systems' },
  { code: 'CSE3323', title: 'Electronics' },
  { code: 'CSE3330', title: 'Database Systems and File Structures' },
  { code: 'CSE3340', title: 'Introduction to Human Computer Interaction' },
  { code: 'CSE3341', title: 'Digital Logic Design II' },
  { code: 'CSE3380', title: 'Linear Algebra for CSE' },
  { code: 'CSE3392', title: 'Special Topics' },
  { code: 'CSE3442', title: 'Embedded Systems I' },
  { code: 'CSE4000', title: 'Senior Undergraduate Research' },
  { code: 'CSE4191', title: 'Individual Projects' },
  { code: 'CSE4303', title: 'Computer Graphics' },
  { code: 'CSE4304', title: 'Game Design and Development' },
  { code: 'CSE4305', title: 'Compilers for Algorithmic Languages' },
  { code: 'CSE4308', title: 'Artificial Intelligence' },
  { code: 'CSE4309', title: 'Fundamentals of Machine Learning' },
  { code: 'CSE4310', title: 'Fundamentals of Computer Vision' },
  { code: 'CSE4311', title: 'Neural Networks and Deep Learning' },
  { code: 'CSE4314', title: 'Professional Practices' },
  { code: 'CSE4316', title: 'Computer System Design Project I' },
  { code: 'CSE4317', title: 'Computer System Design Project II' },
  { code: 'CSE4321', title: 'Software Testing & Matienance' },
  { code: 'CSE4322', title: 'Software Project Management' },
  { code: 'CSE4323', title: 'Quantitative Computer Architecture' },
  { code: 'CSE4331', title: 'Database Implemetation and Theory' },
  { code: 'CSE4333', title: 'Cloud Computing Fundamentals and Applications' },
  { code: 'CSE4334', title: 'Data Mining' },
  { code: 'CSE4340', title: 'Fundamentals of Wireless Networks' },
  { code: 'CSE4342', title: 'Embedded Systems II' },
  { code: 'CSE4344', title: 'Computer Network Organization' },
  { code: 'CSE4345', title: 'Computational Methods' },
  { code: 'CSE4351', title: 'Parallel Processing' },
  { code: 'CSE4352', title: 'IOT and Networking' },
  { code: 'CSE4354', title: 'Real-Time Operating Systems' },
  { code: 'CSE4355', title: 'Electromechanical Systems and Sensors' },
  { code: 'CSE4356', title: 'System on Chip (SOC) Design' },
  { code: 'CSE4358', title: 'Microprocessor Systems' },
  { code: 'CSE4360', title: 'Autonomous Robot Design and Programming' },
  { code: 'CSE4361', title: 'Software Design Patterns' },
  { code: 'CSE4372', title: 'RISC Processor Design' },
  { code: 'CSE4373', title: 'General Purpose GPU Programming' },
  { code: 'CSE4376', title: 'Digital Communication Systems' },
  { code: 'CSE4377', title: 'Wireless Communication Systems' },
  { code: 'CSE4378', title: 'Introduction to Unmanned Vehicle Systems' },
  { code: 'CSE4379', title: 'Unmanned Vehicle System Development' },
  { code: 'CSE4380', title: 'Information Security' },
  { code: 'CSE4381', title: 'Information Security II' },
  { code: 'CSE4382', title: 'Secure Programming' },
  { code: 'CSE4391', title: 'Individual Projects' },
  { code: 'CSE4392', title: 'Special Topics' },
  { code: 'CSE5191', title: 'Individual Study In Computer Science' },
  { code: 'CSE5192', title: 'Individual Study in Computer Science' },
  { code: 'CSE5194', title: 'Orientation Seminar' },
  { code: 'CSE5300', title: 'Fundation of Computing' },
  { code: 'CSE5301', title: 'Data Analysis & Modeling Techniques' },
  { code: 'CSE5305', title: 'Fundations of Graduate Level Studies in Computer Science' },
  { code: 'CSE5306', title: 'Distributed Systems' },
  { code: 'CSE5307', title: 'Programming Langauge Concepts' },
  { code: 'CSE5311', title: 'Design and Analysis of Algorithms' },
  { code: 'CSE5314', title: 'Computational Complexity' },
  { code: 'CSE5315', title: 'Numerical Methods' },
  { code: 'CSE5316', title: 'Modeling, Analysis, and Simulation of Computer Systems' },
  { code: 'CSE5317', title: 'Design and Construction of Compilers' },
  { code: 'CSE5318', title: 'Applied Graph Theory and Combinatorics' },
  { code: 'CSE5319', title: 'Special Topics in Theory & Algorithms' },
  { code: 'CSE5320', title: 'Special Topics in Software Engineering' },
  { code: 'CSE5321', title: 'Software Testing' },
  { code: 'CSE5322', title: 'Software Design Patterns' },
  { code: 'CSE5323', title: 'Software Engineering Processes' },
  { code: 'CSE5324', title: 'Software Engineering: Analysis, Design, and Testing' },
  { code: 'CSE5325', title: 'Software Engineering: Management, Matienance, and Quality Assurance' },
  { code: 'CSE5326', title: 'Real-Time Software Design' },
  { code: 'CSE5327', title: 'Telecommunications Software Development' },
  { code: 'CSE5328', title: 'Sofrware Engineering Team Project I' },
  { code: 'CSE5329', title: 'Software Engineering Team Project II' },
  { code: 'CSE5330', title: 'Database Systems' },
  { code: 'CSE5331', title: 'DBMS Models and Implementation Techniques' },
  { code: 'CSE5332', title: 'Data Science' },
  { code: 'CSE5333', title: 'Cloud Computing' },
  { code: 'CSE5334', title: 'Data Mining' },
  { code: 'CSE5335', title: 'Web Data Management' },
  { code: 'CSE5339', title: 'Special Topics in Database Systems' },
  { code: 'CSE5342', title: 'Embedded Systems II' },
  { code: 'CSE5344', title: 'Computer Networks' },
  { code: 'CSE5345', title: 'Fundamentals of Wireless Networks' },
  { code: 'CSE5346', title: 'Networks II' },
  { code: 'CSE5347', title: 'Fundamentals of Blockchain and Cryptocurrency Technologies' },
  { code: 'CSE5348', title: 'Multimedia Systems' },
  { code: 'CSE5349', title: 'Special Topics in Networking' },
  { code: 'CSE5350', title: 'Computer Architecture II' },
  { code: 'CSE5351', title: 'Parallel Processing' },
  { code: 'CSE5352', title: 'IoT and Networking' },
  { code: 'CSE5353', title: 'Distributed Computing' },
  { code: 'CSE5354', title: 'Real-Time Operating Systems' },
  { code: 'CSE5355', title: 'Electromechanical Systems and Sensors' },
  { code: 'CSE5356', title: 'System on Chip (SoC) Design' },
  { code: 'CSE5357', title: 'Advanced Digital Logic Design' },
  { code: 'CSE5359', title: 'Microprocessor Systems' },
  { code: 'CSE5359', title: 'Special Topics in Systems and Architecture' },
  { code: 'CSE5360', title: 'Artificial Intelligence I' },
  { code: 'CSE5361', title: 'Artificial Intelligence II' },
  { code: 'CSE5362', title: 'Social Networks and Search Engines' },
  { code: 'CSE5364', title: 'Robotics' },
  { code: 'CSE5365', title: 'Computer Graphics' },
  { code: 'CSE5366', title: 'Digitial Signal Processing' },
  { code: 'CSE5367', title: 'Pattern Recognition' },
  { code: 'CSE5368', title: 'Neural Networks' },
  { code: 'CSE5369', title: 'Special Topics in Intelligent Systems' },
  { code: 'CSE5370', title: 'Bioinformatics' },
  { code: 'CSE5372', title: 'RISC Processor Design' },
  { code: 'CSE5373', title: 'General Purpose GPU Programming' },
  { code: 'CSE5376', title: 'Digital Communication Systems' },
  { code: 'CSE5377', title: 'Wireless Communication Systems' },
  { code: 'CSE5379', title: 'Special Topics in Bioinformatics' },
  { code: 'CSE5380', title: 'Information Security' },
  { code: 'CSE5381', title: 'Information Security 2' },
  { code: 'CSE5382', title: 'Secure Programming' },
  { code: 'CSE5383', title: 'Introduction to Unmanned Vehicle Systems' },
  { code: 'CSE5384', title: 'Unmanned Vehicle System Development' },
  { code: 'CSE5388', title: 'Special Topics in Information Security' },
  { code: 'CSE5389', title: 'Special Topics in Multimedia, Graphics, & Image Processing' },
  { code: 'CSE5391', title: 'Individual Study in Computer Science' },
  { code: 'CSE5392', title: 'Topics in Computer Science' },
  { code: 'CSE5393', title: 'Directed Study in Computer Science' },
  { code: 'CSE5394', title: 'Master\'s Project I' },
  { code: 'CSE5395', title: 'Master\'s Project II' },
  { code: 'CSE5398', title: 'Master\'s Thesis I' },
  { code: 'CSE5400', title: 'Fundamentals of Computer Engineering' },
  { code: 'CSE5698', title: 'Master\'s Thesis II' },
  { code: 'CSE6197', title: 'Research in Computer Science' },
  { code: 'CSE6297', title: 'Research in Computer Science' },
  { code: 'CSE6306', title: 'Advanced Topics in Operating Systems' },
  { code: 'CSE6311', title: 'Advanced Computational Models and Algorithms' },
  { code: 'CSE6314', title: 'Advanced Topics in Theoretical Computer Science' },
  { code: 'CSE6319', title: 'Special Topics in Advanced Theory and Algorithms' },
  { code: 'CSE6321', title: 'Advanced Automation Testing' },
  { code: 'CSE6323', title: 'Agile Software Development' },
  { code: 'CSE6324', title: 'Advanced Topics in Software Engineering' },
  { code: 'CSE6329', title: 'Special Topics in Advanced Software Engineering' },
  { code: 'CSE6331', title: 'Advanced Topics in Database Systems' },
  { code: 'CSE6332', title: 'Cloud Computing & Big Data' },
  { code: 'CSE6339', title: 'Special Topics in Advanced Database Systems' },
  { code: 'CSE6344', title: 'Advanced Topics in Communication Networks' },
  { code: 'CSE6345', title: 'Pervasice Computing & Communications' },
  { code: 'CSE6347', title: 'Advanced Wireless Networks & Mobile Computing' },
  { code: 'CSE6348', title: 'Advances in Sensor Networks' },
  { code: 'CSE6349', title: 'Special Topics in Advanced Networking' },
  { code: 'CSE6350', title: 'Advanced Topics in Computer Architecture' },
  { code: 'CSE6351', title: 'Advanced Topics in Computer Engineering' },
  { code: 'CSE6352', title: 'Fault-Tolerant Computing' },
  { code: 'CSE6353', title: 'Computer Engineering System Design' },
  { code: 'CSE6359', title: 'Advanced Topics in Systems & Architecture' },
  { code: 'CSE6362', title: 'Advanced Topics in Artificial Intelligence' },
  { code: 'CSE6363', title: 'Machine Learning' },
  { code: 'CSE6364', title: 'Machine Learning' },
  { code: 'CSE6366', title: 'Digital Image Processing' },
  { code: 'CSE6367', title: 'Computer Vision' },
  { code: 'CSE6368', title: 'Computer Vision' },
  { code: 'CSE6369', title: 'Special Topics Advanced Intelligent Systems' },
  { code: 'CSE6379', title: 'Special Topics in Advanced Bioinformatics' },
  { code: 'CSE6388', title: 'Special Topics in Advanced Information Security' },
  { code: 'CSE6389', title: 'Special Topics in Advanced Multimedia, Graphics, & Image Processing' },
  { code: 'CSE6392', title: 'Speical Topics in Advanced Computer Science' },
  { code: 'CSE6397', title: 'Research in Computer Science' },
  { code: 'CSE6399', title: 'Dissertation' },
  { code: 'CSE6697', title: 'Research in Computer Science' },
  { code: 'CSE6699', title: 'Dissertation' },
  { code: 'CSE6997', title: 'Research in Computer Science' },
  { code: 'CSE6999', title: 'Dissertation' },
  { code: 'CSE7399', title: 'Doctoral Degree Completion' }

];

const seed = async () => {
  try {
    await mongoose.connect(process.env.DB, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });

    await Course.deleteMany(); //optional
    await Course.insertMany(courses);

    console.log('Courses seeded successfully!');
  } catch (err) {
    console.error('Seeding failed:', err);
  } finally {
    await mongoose.disconnect();
  }
};

seed();
